# Based on test repo config https://github.com/decaporg/decap-cms/blob/main/dev-test/config.yml

local_backend: true
# Use DecapBridge auth (required)
backend:
  name: git-gateway
  repo: EscapingAmazon/mm-starter
  branch: setup
  # identity_url: https://auth.decapbridge.com/sites/4ee4960b-ba15-45fc-9f87-e394942b98ad
  # gateway_url: https://gateway.decapbridge.com

  # Quickly see who did what (optional)
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

# Better Decap + Bridge logo (optional)
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

# Add site links in DecapCMS (optional)
site_url: https://escapingamazon.github.io


publish_mode: editorial_workflow
media_folder: /assets/images

aliases:
  - &BODY {name: 'body',
        label: 'Body',
        widget: 'markdown'}
  - &HERO {label: 'Header', 
          name: 'header',
          required: false,
          widget: object,
          fields: [
            {label: 'Image', name: 'overlay_image', widget: 'image', allow_multiple: false, required: false},
            {label: 'Teaser', name: 'teaser', widget: 'image', allow_multiple: false, required: false},
            {label: 'Overlay Color', name: 'overlay_color', widget: 'color', default: '#000000', allowInput: true, required: false, hint: 'Required if using an image'},
            {label: 'Overlay Filter', name: 'overlay_filter', widget: 'number', default: 0, value_type: float, min: 0, max: 1, step: .05, required: false, hint: 'Required if using an image. 0 = No Overlay, 1 = Opaque Overlay'},
            {label: 'Actions', name: 'actions', widget: list, optional: true, fields: [
              {label: 'Button Label', name: 'label', widget: string},
              {label: 'Button URL', name: 'url', widget: string, hint: 'Usually in the form ```/collection/page-name/```, which goes after the primary URL. Can also be an external URL'}
              ]
            }
            ]
          }
  - &TOC {label: "Use TOC", 
          name: 'toc', 
          widget: 'boolean', 
          default: false}
  - &TOC_STICK {label: "Sticky TOC", name: 'toc_sticky', widget: 'boolean', default: false, required: false}
  - &TOC_LABEL {label: "TOC Label", name: 'toc_label', widget: 'string', default: "Table of Contents", required: false}

collections: # A list of collections the CMS should be able to edit.  See here for how to use collections: https://ben.balter.com/2015/02/20/jekyll-collections/
  - name: 'posts' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Posts' # Used in the UI
    label_singular: 'Post' # Used in the UI, ie: "New Post"
    description: >
      Chronological updates, i.e., blog posts.  Not for formal documentation nor lists of links/resources.
    folder: '_posts'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    summary: '{{title}} -- {{year}}/{{month}}/{{day}}'
    create: true # Allow users to create new documents in this collection
    editor:
      visualEditing: true
    view_filters:
      # - label: Posts With Index
      #   field: title
      #   pattern: 'This is post #'
      # - label: Posts Without Index
      #   field: title
      #   pattern: front matter post
      - label: Drafts
        field: draft
        pattern: true
      - label: Released
        field: draft
        pattern: false
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
      - label: Drafts
        field: draft
    fields: # The fields each document in this collection have
      - { label: 'Categories', name: 'categories', widget: 'hidden', default: 'Blog'}
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: true }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          format: 'YYYY-MM-DD HH:mm',
          default: '{{now}}',
        }
      - { label: 'Tags', name: 'tags', widget: 'list', default: ["blog"] }
      - label: 'Cover Image'
        name: 'image'
        widget: 'image'
        required: false
        tagname: ''

      - { label: 'Body', name: 'body', widget: 'markdown', hint: 'Main content goes here.' }

  - name: 'guides' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Guides' # Used in the UI
    label_singular: 'Guide' # Used in the UI, ie: "New Post"
    folder: '_guides'
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - { label: 'Instructions', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list', default: ["guide"] }

  # - name: 'faq' # Used in routes, ie.: /admin/collections/:slug/edit
  #   label: 'FAQ' # Used in the UI
  #   folder: '_faqs'
  #   create: true # Allow users to create new documents in this collection
  #   fields: # The fields each document in this collection have
  #     - { label: 'Question', name: 'title', widget: 'string', tagname: 'h1' }
  #     - { label: 'Answer', name: 'body', widget: 'markdown' }

  - name: 'settings'
    label: 'Settings'
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: 'general'
        label: 'Site Settings'
        file: '_data/settings.json'
        description: 'General Site Settings'
        fields:
          - { label: 'Global title', name: 'site_title', widget: 'string' }
          - label: 'Post Settings'
            name: posts
            widget: 'object'
            fields:
              - {
                  label: 'Number of posts on frontpage',
                  name: front_limit,
                  widget: number,
                  min: 1,
                  max: 10,
                }
              - { label: 'Default Author', name: author, widget: string }
              - {
                  label: 'Default Thumbnail',
                  name: thumb,
                  widget: image,
                  class: 'thumb',
                  required: false,
                }

      - name: 'authors'
        label: 'Authors'
        file: '_data/authors.yml'
        description: 'Author descriptions'
        fields:
          - name: authors
            label: Authors
            label_singular: 'Author'
            widget: list
            fields:
              - { label: 'Name', name: 'name', widget: 'string', hint: 'First and Last' }
              - { label: 'Description', name: 'description', widget: 'markdown' }
  - name: pages # a nested collection
    label: Pages
    label_singular: 'Page'
    folder: _pages
    create: true
    nested: { depth: 100, subfolders: false }
    fields:
      - label: Title
        name: title
        widget: string
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }

  - name: about
    label: "About Pages"
    label_singular: "About Page"
    folder: _about
    description: "Informational pages for viewers of the project"
    delete: false
    editor:
      preview: true
    create: true # Allow users to create new documents in this collection
    # editor:
    #   visualEditing: true
    view_filters:
      - label: Drafts
        field: draft
        pattern: true
      - label: Released
        field: draft
        pattern: false
    fields: # The fields each document in this collection have
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - << : *HERO
      - {label: 'Tagline', name: 'tagline', required: False, widget: 'text'}
      - << : *TOC
      - << : *TOC_STICK
      - << : *TOC_LABEL
      - << : *BODY
     
      # - label: 'Header' 
      #   name: 'header'
      #   widget: object
      #   fields:
      #   - {label: 'Image', name: 'image', widget: 'image', allow_multiple: false,required: false}
      #   - {label: 'Teaser', name: 'teaser', widget: 'image', allow_multiple: false,required: false}
      # - { label: 'Draft', name: 'draft', widget: 'boolean', default: true }
      # - { label: 'Layout', name: 'layout', widget: 'select', options: ["archive-taxonomy","archive","categories","category","collection","compress","default","home","posts","search","single","splash","tag","tags"]}
      # - { label: 'Body', name: 'body', widget: 'markdown', hint: 'Main content goes here.' }

  - name: tester
    label: tester
    folder: _tester
    create: true
    fields:
      - name: title
        label: Title
        widget: string
      # - name: categories
      #   label: Categories
      #   widget: categories
      #   separator: __
      - << : *HERO
      - name: 'body'
        label: 'Body'
        widget: 'markdown'





  # - name: 'kitchenSink' # all the things in one entry, for documentation and quick testing
  #   label: 'Kitchen Sink'
  #   folder: '_sink'
  #   create: true
  #   fields:
  #     - label: 'Related Post'
  #       name: 'post'
  #       widget: 'relationKitchenSinkPost'
  #       collection: 'posts'
  #       display_fields: ['title', 'datetime']
  #       search_fields: ['title', 'body']
  #       value_field: 'title'
  #     - { label: 'Title', name: 'title', widget: 'string' }
  #     - { label: 'Boolean', name: 'boolean', widget: 'boolean', default: true }
  #     - { label: 'Map', name: 'map', widget: 'map' }
  #     - { label: 'Text', name: 'text', widget: 'text', hint: 'Plain text, not markdown' }
  #     - { label: 'Number', name: 'number', widget: 'number', hint: 'To infinity and beyond!' }
  #     - { label: 'Markdown', name: 'markdown', widget: 'markdown' }
  #     - { label: 'Datetime', name: 'datetime', widget: 'datetime' }
  #     - { label: 'Image', name: 'image', widget: 'image' }
  #     - { label: 'File', name: 'file', widget: 'file' }
  #     - { label: 'Select', name: 'select', widget: 'select', options: ['a', 'b', 'c'] }
  #     - {
  #         label: 'Select multiple',
  #         name: 'select_multiple',
  #         widget: 'select',
  #         options: ['a', 'b', 'c'],
  #         multiple: true,
  #       }
  #     - { label: 'Hidden', name: 'hidden', widget: 'hidden', default: 'hidden' }
  #     - { label: 'Color', name: 'color', widget: 'color' }
  #     - label: 'Object'
  #       name: 'object'
  #       widget: 'object'
  #       collapsed: true
  #       fields:
  #         - label: 'Related Post'
  #           name: 'post'
  #           widget: 'relationKitchenSinkPost'
  #           collection: 'posts'
  #           search_fields: ['title', 'body']
  #           value_field: 'title'
  #         - { label: 'String', name: 'string', widget: 'string' }
  #         - { label: 'Boolean', name: 'boolean', widget: 'boolean', default: false }
  #         - { label: 'Text', name: 'text', widget: 'text' }
  #         - { label: 'Number', name: 'number', widget: 'number' }
  #         - { label: 'Markdown', name: 'markdown', widget: 'markdown' }
  #         - { label: 'Datetime', name: 'datetime', widget: 'datetime' }
  #         - { label: 'Image', name: 'image', widget: 'image' }
  #         - { label: 'File', name: 'file', widget: 'file' }
  #         - { label: 'Select', name: 'select', widget: 'select', options: ['a', 'b', 'c'] }
  #     - label: 'List'
  #       name: 'list'
  #       widget: 'list'
  #       fields:
  #         - { label: 'String', name: 'string', widget: 'string' }
  #         - { label: 'Boolean', name: 'boolean', widget: 'boolean' }
  #         - { label: 'Text', name: 'text', widget: 'text' }
  #         - { label: 'Number', name: 'number', widget: 'number' }
  #         - { label: 'Markdown', name: 'markdown', widget: 'markdown' }
  #         - { label: 'Datetime', name: 'datetime', widget: 'datetime' }
  #         - { label: 'Image', name: 'image', widget: 'image' }
  #         - { label: 'File', name: 'file', widget: 'file' }
  #         - { label: 'Select', name: 'select', widget: 'select', options: ['a', 'b', 'c'] }
  #         - label: 'Object'
  #           name: 'object'
  #           widget: 'object'
  #           fields:
  #             - { label: 'String', name: 'string', widget: 'string' }
  #             - { label: 'Boolean', name: 'boolean', widget: 'boolean' }
  #             - { label: 'Text', name: 'text', widget: 'text' }
  #             - { label: 'Number', name: 'number', widget: 'number' }
  #             - { label: 'Markdown', name: 'markdown', widget: 'markdown' }
  #             - { label: 'Datetime', name: 'datetime', widget: 'datetime' }
  #             - { label: 'Image', name: 'image', widget: 'image' }
  #             - { label: 'File', name: 'file', widget: 'file' }
  #             - { label: 'Select', name: 'select', widget: 'select', options: ['a', 'b', 'c'] }
  #             - label: 'List'
  #               name: 'list'
  #               widget: 'list'
  #               fields:
  #                 - label: 'Related Post'
  #                   name: 'post'
  #                   widget: 'relationKitchenSinkPost'
  #                   collection: 'posts'
  #                   search_fields: ['title', 'body']
  #                   value_field: 'title'
  #                 - { label: 'String', name: 'string', widget: 'string' }
  #                 - { label: 'Boolean', name: 'boolean', widget: 'boolean' }
  #                 - { label: 'Text', name: 'text', widget: 'text' }
  #                 - { label: 'Number', name: 'number', widget: 'number' }
  #                 - { label: 'Markdown', name: 'markdown', widget: 'markdown' }
  #                 - { label: 'Datetime', name: 'datetime', widget: 'datetime' }
  #                 - { label: 'Image', name: 'image', widget: 'image' }
  #                 - { label: 'File', name: 'file', widget: 'file' }
  #                 - { label: 'Select', name: 'select', widget: 'select', options: ['a', 'b', 'c'] }
  #                 - { label: 'Hidden', name: 'hidden', widget: 'hidden', default: 'hidden' }
  #                 - label: 'Object'
  #                   name: 'object'
  #                   widget: 'object'
  #                   fields:
  #                     - { label: 'String', name: 'string', widget: 'string' }
  #                     - { label: 'Boolean', name: 'boolean', widget: 'boolean' }
  #                     - { label: 'Text', name: 'text', widget: 'text' }
  #                     - { label: 'Number', name: 'number', widget: 'number' }
  #                     - { label: 'Markdown', name: 'markdown', widget: 'markdown' }
  #                     - { label: 'Datetime', name: 'datetime', widget: 'datetime' }
  #                     - { label: 'Image', name: 'image', widget: 'image' }
  #                     - { label: 'File', name: 'file', widget: 'file' }
  #                     - {
  #                         label: 'Select',
  #                         name: 'select',
  #                         widget: 'select',
  #                         options: ['a', 'b', 'c'],
  #                       }
  #     - label: 'Typed List'
  #       name: 'typed_list'
  #       widget: 'list'
  #       types:
  #         - label: 'Type 1 Object'
  #           name: 'type_1_object'
  #           widget: 'object'
  #           fields:
  #             - { label: 'String', name: 'string', widget: 'string' }
  #             - { label: 'Boolean', name: 'boolean', widget: 'boolean' }
  #             - { label: 'Text', name: 'text', widget: 'text' }
  #         - label: 'Type 2 Object'
  #           name: 'type_2_object'
  #           widget: 'object'
  #           fields:
  #             - { label: 'Number', name: 'number', widget: 'number' }
  #             - { label: 'Select', name: 'select', widget: 'select', options: ['a', 'b', 'c'] }
  #             - { label: 'Datetime', name: 'datetime', widget: 'datetime' }
  #             - { label: 'Markdown', name: 'markdown', widget: 'markdown' }
  #         - label: 'Type 3 Object'
  #           name: 'type_3_object'
  #           widget: 'object'
  #           fields:
  #             - { label: 'Image', name: 'image', widget: 'image' }
  #             - { label: 'File', name: 'file', widget: 'file' }
